import { pgTable, uuid, varchar, numeric, text, timestamp, integer, boolean, date } from 'drizzle-orm/pg-core';
// import { users } from '../core/users.schema';
import { fund_managers, distributors, users } from '@infrastructure/schemas';
// import { distributors } from '../distributor.schema';

export const investmentSnapshot = pgTable('investment_snapshot', {
  id: uuid('id').primaryKey().defaultRandom(),
  investmentId: uuid('investment_id'),
  investmentAccountId: uuid('investment_account_id'),
  snapshotVersion: integer('snapshot_version').default(1).notNull(),
  parentSnapshotId: uuid('parent_snapshot_id'),
  // Snapshot of investments fields
  productId: uuid('product_id'),
  productName: varchar('product_name', { length: 255 }),
  amcId: uuid('amc_id'),
  amcName: varchar('amc_name', { length: 255 }),
  amcCode: varchar('amc_code', { length: 50 }),
  amcClientCode: varchar('amc_client_code', { length: 50 }),
  schemeId: uuid('scheme_id'),
  schemeCode: varchar('scheme_code', { length: 50 }),
  schemeName: varchar('scheme_name', { length: 100 }),
  fmId: uuid('fm_id').references(() => fund_managers.id),
  fmCode: varchar('fm_code', { length: 50 }),
  fmName: varchar('fm_name', { length: 100 }),
  branchCode: varchar('branch_code', { length: 50 }),
  amcSharing: numeric('amc_sharing', { precision: 5, scale: 2 }),
  feeStructure: text('fee_structure'),
  fixedFee: varchar('fixed_fee'),
  variableFee: varchar('variable_fee'),
  performanceFee: varchar('performance_fee'),
  hurdleFee: varchar('hurdle_fee'),
  drawdownNo: varchar('drawdown_no'),
  remarks: text('remarks'),
  distributorId: uuid('distributor_id').references(() => distributors.id),
  distributorCode: varchar('distributor_code', { length: 50 }),
  distributorName: varchar('distributor_name', { length: 100 }),
  creId: uuid('cre_id').references(() => users.id),
  creCode: varchar('cre_code', { length: 50 }),
  creName: varchar('cre_name', { length: 100 }),
  rmId: uuid('rm_id').references(() => users.id),
  rmCode: varchar('rm_code', { length: 50 }),
  rmName: varchar('rm_name', { length: 100 }),
  capitalCommitment: numeric('capital_commitment', { precision: 20, scale: 2 }),
  currency: varchar('currency', { length: 10 }),
  inceptionDate: date('inception_date', { mode: 'string' }),
  status: varchar('status', { length: 30 }),
  isLatest: boolean('is_latest').default(false),
  snapshotReason: varchar('snapshot_reason', { length: 255 }),
  capturedAt: timestamp('captured_at').defaultNow(),
});